language: rust
rust: nightly

os:
  - linux
  - osx
  - windows

cache:
  yarn: true
  cargo: true
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm
    - snapcraft
    - flatpak-builder

before_install:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install nvm; fi
  - nvm install lts/carbon

script:
  - yarn
  - yarn lint
  - if test -z "$TRAVIS_TAG"; then travis_wait yarn make; fi

after_success:
  - if test -n "$TRAVIS_TAG"; then yarn publish; fi
